// ecosystem.config.cjs
module.exports = {
  apps: [
    {
      name: "kowloon",
      script: "index.js",
      watch: true,
      watch_options: {
        followSymlinks: false,
        usePolling: false,
      },
      ignore_watch: [
        "node_modules",
        "logs",
        ".git",
        "*.log",
        "*.pid",
        ".DS_Store",
        "tests",
        "test-*.js",
      ],
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "500M",
    },
    {
      name: "kowloon-worker-feed",
      script: "workers/feedFanOut.js",
      watch: true,
      watch_options: {
        followSymlinks: false,
        usePolling: false,
      },
      ignore_watch: [
        "node_modules",
        "logs",
        ".git",
        "*.log",
        "*.pid",
        ".DS_Store",
        "tests",
        "test-*.js",
      ],
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      max_memory_restart: "200M",
    },
    // {
    //   name: "kowloon-worker-pull",
    //   script: "workers/pullScheduler.js",
    //   watch: false,
    //   time: true,
    //   autorestart: true,
    //   max_restarts: 10,
    // },
  ],
  deploy: {
    dev1: {
      user: "jzellis",
      host: "kowloon.network",
      port: 22,
      ref: "origin/main",
      repo: "git@github.com:jzellis/kowloon.git",
      path: "/home/jzellis/kowloon",
      ssh_options: "StrictHostKeyChecking=no",
      "post-deploy":
        "/home/jzellis/.nvm/versions/node/v24.7.0/bin/pnpm install --no-frozen-lockfile && /home/jzellis/.nvm/versions/node/v24.7.0/bin/pm2 startOrReload ecosystem.config.cjs --env dev1",
    },
    dev2: {
      user: "jzellis",
      host: "kwln.social",
      port: 22,
      ref: "origin/main",
      repo: "git@github.com:jzellis/kowloon.git",
      path: "/home/jzellis/kowloon",
      ssh_options: "StrictHostKeyChecking=no",
      "post-deploy":
        "/home/jzellis/.nvm/versions/node/v24.7.0/bin/pnpm install --no-frozen-lockfile && /home/jzellis/.nvm/versions/node/v24.7.0/bin/pm2 startOrReload ecosystem.config.cjs --env dev2",
    },
  },
};
