import { faker } from "@faker-js/faker";
import fs from "fs/promises";

let users = [
  {
    id: "@johnny_doe12@example.com",
    name: "Johnny Doe",
    type: "kowloon",
    inbox: "https://example.com/@johnny_doe12@example.com/inbox",
    outbox: "https://example.com/@johnny_doe12@example.com/outbox",
  },
  {
    id: "@amanda_kelly34@mail.com",
    name: "Amanda Kelly",
    type: "kowloon",
    inbox: "https://mail.com/@amanda_kelly34@mail.com/inbox",
    outbox: "https://mail.com/@amanda_kelly34@mail.com/outbox",
  },
  {
    id: "@kevin_smith567@outlook.com",
    name: "Kevin Smith",
    type: "kowloon",
    inbox: "https://outlook.com/@kevin_smith567@outlook.com/inbox",
    outbox: "https://outlook.com/@kevin_smith567@outlook.com/outbox",
  },
  {
    id: "@sarah_jameson88@gmail.com",
    name: "Sarah Jameson",
    type: "kowloon",
    inbox: "https://gmail.com/@sarah_jameson88@gmail.com/inbox",
    outbox: "https://gmail.com/@sarah_jameson88@gmail.com/outbox",
  },
  {
    id: "@lisa_carter321@yahoo.com",
    name: "Lisa Carter",
    type: "kowloon",
    inbox: "https://yahoo.com/@lisa_carter321@yahoo.com/inbox",
    outbox: "https://yahoo.com/@lisa_carter321@yahoo.com/outbox",
  },
  {
    id: "@mark_wilson45@hotmail.com",
    name: "Mark Wilson",
    type: "kowloon",
    inbox: "https://hotmail.com/@mark_wilson45@hotmail.com/inbox",
    outbox: "https://hotmail.com/@mark_wilson45@hotmail.com/outbox",
  },
  {
    id: "@ellen_walker987@aol.com",
    name: "Ellen Walker",
    type: "kowloon",
    inbox: "https://aol.com/@ellen_walker987@aol.com/inbox",
    outbox: "https://aol.com/@ellen_walker987@aol.com/outbox",
  },
  {
    id: "@samuel_peters46@protonmail.com",
    name: "Samuel Peters",
    type: "kowloon",
    inbox: "https://protonmail.com/@samuel_peters46@protonmail.com/inbox",
    outbox: "https://protonmail.com/@samuel_peters46@protonmail.com/outbox",
  },
  {
    id: "@jessica_hughes72@mail.com",
    name: "Jessica Hughes",
    type: "kowloon",
    inbox: "https://mail.com/@jessica_hughes72@mail.com/inbox",
    outbox: "https://mail.com/@jessica_hughes72@mail.com/outbox",
  },
  {
    id: "@david_smith202@icloud.com",
    name: "David Smith",
    type: "kowloon",
    inbox: "https://icloud.com/@david_smith202@icloud.com/inbox",
    outbox: "https://icloud.com/@david_smith202@icloud.com/outbox",
  },
  {
    id: "@michael_reed66@yahoo.com",
    name: "Michael Reed",
    type: "kowloon",
    inbox: "https://yahoo.com/@michael_reed66@yahoo.com/inbox",
    outbox: "https://yahoo.com/@michael_reed66@yahoo.com/outbox",
  },
  {
    id: "@lucy_hamilton19@outlook.com",
    name: "Lucy Hamilton",
    type: "kowloon",
    inbox: "https://outlook.com/@lucy_hamilton19@outlook.com/inbox",
    outbox: "https://outlook.com/@lucy_hamilton19@outlook.com/outbox",
  },
  {
    id: "@olivia_morris23@gmail.com",
    name: "Olivia Morris",
    type: "kowloon",
    inbox: "https://gmail.com/@olivia_morris23@gmail.com/inbox",
    outbox: "https://gmail.com/@olivia_morris23@gmail.com/outbox",
  },
  {
    id: "@benjamin_cook49@aol.com",
    name: "Benjamin Cook",
    type: "kowloon",
    inbox: "https://aol.com/@benjamin_cook49@aol.com/inbox",
    outbox: "https://aol.com/@benjamin_cook49@aol.com/outbox",
  },
  {
    id: "@hannah_clark92@icloud.com",
    name: "Hannah Clark",
    type: "kowloon",
    inbox: "https://icloud.com/@hannah_clark92@icloud.com/inbox",
    outbox: "https://icloud.com/@hannah_clark92@icloud.com/outbox",
  },
  {
    id: "@jake_davis101@gmail.com",
    name: "Jake Davis",
    type: "kowloon",
    inbox: "https://gmail.com/@jake_davis101@gmail.com/inbox",
    outbox: "https://gmail.com/@jake_davis101@gmail.com/outbox",
  },
  {
    id: "@rebecca_white34@hotmail.com",
    name: "Rebecca White",
    type: "kowloon",
    inbox: "https://hotmail.com/@rebecca_white34@hotmail.com/inbox",
    outbox: "https://hotmail.com/@rebecca_white34@hotmail.com/outbox",
  },
  {
    id: "@andrew_sanchez11@mail.com",
    name: "Andrew Sanchez",
    type: "kowloon",
    inbox: "https://mail.com/@andrew_sanchez11@mail.com/inbox",
    outbox: "https://mail.com/@andrew_sanchez11@mail.com/outbox",
  },
  {
    id: "@chloe_baker55@protonmail.com",
    name: "Chloe Baker",
    type: "kowloon",
    inbox: "https://protonmail.com/@chloe_baker55@protonmail.com/inbox",
    outbox: "https://protonmail.com/@chloe_baker55@protonmail.com/outbox",
  },
  {
    id: "@charles_johnson82@outlook.com",
    name: "Charles Johnson",
    type: "kowloon",
    inbox: "https://outlook.com/@charles_johnson82@outlook.com/inbox",
    outbox: "https://outlook.com/@charles_johnson82@outlook.com/outbox",
  },
  {
    id: "@paul_lee23@aol.com",
    name: "Paul Lee",
    type: "kowloon",
    inbox: "https://aol.com/@paul_lee23@aol.com/inbox",
    outbox: "https://aol.com/@paul_lee23@aol.com/outbox",
  },
  {
    id: "@kimberly_turner44@gmail.com",
    name: "Kimberly Turner",
    type: "kowloon",
    inbox: "https://gmail.com/@kimberly_turner44@gmail.com/inbox",
    outbox: "https://gmail.com/@kimberly_turner44@gmail.com/outbox",
  },
  {
    id: "@noah_wright65@icloud.com",
    name: "Noah Wright",
    type: "kowloon",
    inbox: "https://icloud.com/@noah_wright65@icloud.com/inbox",
    outbox: "https://icloud.com/@noah_wright65@icloud.com/outbox",
  },
  {
    id: "@sofia_miller98@yahoo.com",
    name: "Sofia Miller",
    type: "kowloon",
    inbox: "https://yahoo.com/@sofia_miller98@yahoo.com/inbox",
    outbox: "https://yahoo.com/@sofia_miller98@yahoo.com/outbox",
  },
  {
    id: "@tommy_jenkins56@aol.com",
    name: "Tommy Jenkins",
    type: "kowloon",
    inbox: "https://aol.com/@tommy_jenkins56@aol.com/inbox",
    outbox: "https://aol.com/@tommy_jenkins56@aol.com/outbox",
  },
  {
    id: "@aiden_scott29@mail.com",
    name: "Aiden Scott",
    type: "kowloon",
    inbox: "https://mail.com/@aiden_scott29@mail.com/inbox",
    outbox: "https://mail.com/@aiden_scott29@mail.com/outbox",
  },
  {
    id: "@bella_thomas32@outlook.com",
    name: "Bella Thomas",
    type: "kowloon",
    inbox: "https://outlook.com/@bella_thomas32@outlook.com/inbox",
    outbox: "https://outlook.com/@bella_thomas32@outlook.com/outbox",
  },
  {
    id: "@zachary_evans71@gmail.com",
    name: "Zachary Evans",
    type: "kowloon",
    inbox: "https://gmail.com/@zachary_evans71@gmail.com/inbox",
    outbox: "https://gmail.com/@zachary_evans71@gmail.com/outbox",
  },
  {
    id: "@grace_king13@yahoo.com",
    name: "Grace King",
    type: "kowloon",
    inbox: "https://yahoo.com/@grace_king13@yahoo.com/inbox",
    outbox: "https://yahoo.com/@grace_king13@yahoo.com/outbox",
  },
  {
    id: "@alexandra_lee40@icloud.com",
    name: "Alexandra Lee",
    type: "kowloon",
    inbox: "https://icloud.com/@alexandra_lee40@icloud.com/inbox",
    outbox: "https://icloud.com/@alexandra_lee40@icloud.com/outbox",
  },
  {
    id: "@thomas_campbell81@protonmail.com",
    name: "Thomas Campbell",
    type: "kowloon",
    inbox: "https://protonmail.com/@thomas_campbell81@protonmail.com/inbox",
    outbox: "https://protonmail.com/@thomas_campbell81@protonmail.com/outbox",
  },
  {
    id: "@victor_adams69@aol.com",
    name: "Victor Adams",
    type: "kowloon",
    inbox: "https://aol.com/@victor_adams69@aol.com/inbox",
    outbox: "https://aol.com/@victor_adams69@aol.com/outbox",
  },
  {
    id: "@amelia_bennett64@mail.com",
    name: "Amelia Bennett",
    type: "kowloon",
    inbox: "https://mail.com/@amelia_bennett64@mail.com/inbox",
    outbox: "https://mail.com/@amelia_bennett64@mail.com/outbox",
  },
  {
    id: "@james_bradley53@gmail.com",
    name: "James Bradley",
    type: "kowloon",
    inbox: "https://gmail.com/@james_bradley53@gmail.com/inbox",
    outbox: "https://gmail.com/@james_bradley53@gmail.com/outbox",
  },
  {
    id: "@lily_harper50@icloud.com",
    name: "Lily Harper",
    type: "kowloon",
    inbox: "https://icloud.com/@lily_harper50@icloud.com/inbox",
    outbox: "https://icloud.com/@lily_harper50@icloud.com/outbox",
  },
  {
    id: "@jordan_russell28@hotmail.com",
    name: "Jordan Russell",
    type: "kowloon",
    inbox: "https://hotmail.com/@jordan_russell28@hotmail.com/inbox",
    outbox: "https://hotmail.com/@jordan_russell28@hotmail.com/outbox",
  },
  {
    id: "@madeline_green77@mail.com",
    name: "Madeline Green",
    type: "kowloon",
    inbox: "https://mail.com/@madeline_green77@mail.com/inbox",
    outbox: "https://mail.com/@madeline_green77@mail.com/outbox",
  },
  {
    id: "@nathaniel_gray22@aol.com",
    name: "Nathaniel Gray",
    type: "kowloon",
    inbox: "https://aol.com/@nathaniel_gray22@aol.com/inbox",
    outbox: "https://aol.com/@nathaniel_gray22@aol.com/outbox",
  },
  {
    id: "@ella_williams12@outlook.com",
    name: "Ella Williams",
    type: "kowloon",
    inbox: "https://outlook.com/@ella_williams12@outlook.com/inbox",
    outbox: "https://outlook.com/@ella_williams12@outlook.com/outbox",
  },
  {
    id: "@william_king57@gmail.com",
    name: "William King",
    type: "kowloon",
    inbox: "https://gmail.com/@william_king57@gmail.com/inbox",
    outbox: "https://gmail.com/@william_king57@gmail.com/outbox",
  },
  {
    id: "@zara_stewart65@yahoo.com",
    name: "Zara Stewart",
    type: "kowloon",
    inbox: "https://yahoo.com/@zara_stewart65@yahoo.com/inbox",
    outbox: "https://yahoo.com/@zara_stewart65@yahoo.com/outbox",
  },
  {
    id: "@ethan_thompson19@icloud.com",
    name: "Ethan Thompson",
    type: "kowloon",
    inbox: "https://icloud.com/@ethan_thompson19@icloud.com/inbox",
    outbox: "https://icloud.com/@ethan_thompson19@icloud.com/outbox",
  },
  {
    id: "@lauren_martinez77@mail.com",
    name: "Lauren Martinez",
    type: "kowloon",
    inbox: "https://mail.com/@lauren_martinez77@mail.com/inbox",
    outbox: "https://mail.com/@lauren_martinez77@mail.com/outbox",
  },
  {
    id: "@jared_evans22@protonmail.com",
    name: "Jared Evans",
    type: "kowloon",
    inbox: "https://protonmail.com/@jared_evans22@protonmail.com/inbox",
    outbox: "https://protonmail.com/@jared_evans22@protonmail.com/outbox",
  },
  {
    id: "@emily_scott14@aol.com",
    name: "Emily Scott",
    type: "kowloon",
    inbox: "https://aol.com/@emily_scott14@aol.com/inbox",
    outbox: "https://aol.com/@emily_scott14@aol.com/outbox",
  },
  {
    id: "@ryan_brown61@outlook.com",
    name: "Ryan Brown",
    type: "kowloon",
    inbox: "https://outlook.com/@ryan_brown61@outlook.com/inbox",
    outbox: "https://outlook.com/@ryan_brown61@outlook.com/outbox",
  },
  {
    id: "@victoria_fisher32@gmail.com",
    name: "Victoria Fisher",
    type: "kowloon",
    inbox: "https://gmail.com/@victoria_fisher32@gmail.com/inbox",
    outbox: "https://gmail.com/@victoria_fisher32@gmail.com/outbox",
  },
  {
    id: "@ian_williams83@mail.com",
    name: "Ian Williams",
    type: "kowloon",
    inbox: "https://mail.com/@ian_williams83@mail.com/inbox",
    outbox: "https://mail.com/@ian_williams83@mail.com/outbox",
  },
  {
    id: "@katherine_garcia49@icloud.com",
    name: "Katherine Garcia",
    type: "kowloon",
    inbox: "https://icloud.com/@katherine_garcia49@icloud.com/inbox",
    outbox: "https://icloud.com/@katherine_garcia49@icloud.com/outbox",
  },
  {
    id: "@max_hughes31@aol.com",
    name: "Max Hughes",
    inbox: "https://aol.com/@max_hughes31@aol.com/inbox",
    outbox: "https://aol.com/@max_hughes31@aol.com/outbox",
  },
];

users.forEach((u) => {
  u.url = faker.internet.url();
});

await fs.writeFile("users.js", JSON.stringify(users), "utf-8");
