import { faker } from "@faker-js/faker";
import { Settings, User, Post, Circle } from "../../schema/index.js";
import Kowloon from "../../Kowloon.js";
export default async function () {
  let baseUrl = `https://${
    (await Settings.findOne({ name: "domain" })).value
  }/inbox`;

  let users = [
    {
      id: "@johnny_doe12@example.com",
      name: "Johnny Doe",
      type: "kowloon",
      inbox: "https://example.com/@johnny_doe12@example.com/inbox",
      outbox: "https://example.com/@johnny_doe12@example.com/outbox",
      serverId: "@example.com",
      url: "https://any-scraper.biz/",
    },
    {
      id: "@amanda_kelly34@mail.com",
      name: "Amanda Kelly",
      type: "kowloon",
      inbox: "https://mail.com/@amanda_kelly34@mail.com/inbox",
      outbox: "https://mail.com/@amanda_kelly34@mail.com/outbox",
      serverId: "@mail.com",
      url: "https://nocturnal-clinic.name/",
    },
    {
      id: "@kevin_smith567@outlook.com",
      name: "Kevin Smith",
      type: "kowloon",
      inbox: "https://outlook.com/@kevin_smith567@outlook.com/inbox",
      outbox: "https://outlook.com/@kevin_smith567@outlook.com/outbox",
      serverId: "@outlook.com",
      url: "https://odd-pup.name",
    },
    {
      id: "@sarah_jameson88@gmail.com",
      name: "Sarah Jameson",
      type: "kowloon",
      inbox: "https://gmail.com/@sarah_jameson88@gmail.com/inbox",
      outbox: "https://gmail.com/@sarah_jameson88@gmail.com/outbox",
      serverId: "@gmail.com",
      url: "https://jumbo-quotation.com/",
    },
    {
      id: "@lisa_carter321@yahoo.com",
      name: "Lisa Carter",
      type: "kowloon",
      inbox: "https://yahoo.com/@lisa_carter321@yahoo.com/inbox",
      outbox: "https://yahoo.com/@lisa_carter321@yahoo.com/outbox",
      serverId: "@yahoo.com",
      url: "https://dead-hint.info",
    },
    {
      id: "@mark_wilson45@hotmail.com",
      name: "Mark Wilson",
      type: "kowloon",
      inbox: "https://hotmail.com/@mark_wilson45@hotmail.com/inbox",
      outbox: "https://hotmail.com/@mark_wilson45@hotmail.com/outbox",
      serverId: "@hotmail.com",
      url: "https://identical-salon.com/",
    },
    {
      id: "@ellen_walker987@aol.com",
      name: "Ellen Walker",
      type: "kowloon",
      inbox: "https://aol.com/@ellen_walker987@aol.com/inbox",
      outbox: "https://aol.com/@ellen_walker987@aol.com/outbox",
      serverId: "@aol.com",
      url: "https://optimistic-kick-off.info",
    },
    {
      id: "@samuel_peters46@protonmail.com",
      name: "Samuel Peters",
      type: "kowloon",
      inbox: "https://protonmail.com/@samuel_peters46@protonmail.com/inbox",
      outbox: "https://protonmail.com/@samuel_peters46@protonmail.com/outbox",
      serverId: "@protonmail.com",
      url: "https://partial-refuge.org/",
    },
    {
      id: "@jessica_hughes72@mail.com",
      name: "Jessica Hughes",
      type: "kowloon",
      inbox: "https://mail.com/@jessica_hughes72@mail.com/inbox",
      outbox: "https://mail.com/@jessica_hughes72@mail.com/outbox",
      serverId: "@mail.com",
      url: "https://jealous-bait.biz",
    },
    {
      id: "@david_smith202@icloud.com",
      name: "David Smith",
      type: "kowloon",
      inbox: "https://icloud.com/@david_smith202@icloud.com/inbox",
      outbox: "https://icloud.com/@david_smith202@icloud.com/outbox",
      serverId: "@icloud.com",
      url: "https://terrific-dig.com/",
    },
    {
      id: "@michael_reed66@yahoo.com",
      name: "Michael Reed",
      type: "kowloon",
      inbox: "https://yahoo.com/@michael_reed66@yahoo.com/inbox",
      outbox: "https://yahoo.com/@michael_reed66@yahoo.com/outbox",
      serverId: "@yahoo.com",
      url: "https://familiar-youth.name/",
    },
    {
      id: "@lucy_hamilton19@outlook.com",
      name: "Lucy Hamilton",
      type: "kowloon",
      inbox: "https://outlook.com/@lucy_hamilton19@outlook.com/inbox",
      outbox: "https://outlook.com/@lucy_hamilton19@outlook.com/outbox",
      serverId: "@outlook.com",
      url: "https://rural-cabana.biz/",
    },
    {
      id: "@olivia_morris23@gmail.com",
      name: "Olivia Morris",
      type: "kowloon",
      inbox: "https://gmail.com/@olivia_morris23@gmail.com/inbox",
      outbox: "https://gmail.com/@olivia_morris23@gmail.com/outbox",
      serverId: "@gmail.com",
      url: "https://creepy-recorder.name/",
    },
    {
      id: "@benjamin_cook49@aol.com",
      name: "Benjamin Cook",
      type: "kowloon",
      inbox: "https://aol.com/@benjamin_cook49@aol.com/inbox",
      outbox: "https://aol.com/@benjamin_cook49@aol.com/outbox",
      serverId: "@aol.com",
      url: "https://dangerous-allocation.com/",
    },
    {
      id: "@hannah_clark92@icloud.com",
      name: "Hannah Clark",
      type: "kowloon",
      inbox: "https://icloud.com/@hannah_clark92@icloud.com/inbox",
      outbox: "https://icloud.com/@hannah_clark92@icloud.com/outbox",
      serverId: "@icloud.com",
      url: "https://serene-commerce.net",
    },
    {
      id: "@jake_davis101@gmail.com",
      name: "Jake Davis",
      type: "kowloon",
      inbox: "https://gmail.com/@jake_davis101@gmail.com/inbox",
      outbox: "https://gmail.com/@jake_davis101@gmail.com/outbox",
      serverId: "@gmail.com",
      url: "https://peppery-pearl.info",
    },
    {
      id: "@rebecca_white34@hotmail.com",
      name: "Rebecca White",
      type: "kowloon",
      inbox: "https://hotmail.com/@rebecca_white34@hotmail.com/inbox",
      outbox: "https://hotmail.com/@rebecca_white34@hotmail.com/outbox",
      serverId: "@hotmail.com",
      url: "https://colorful-theory.org/",
    },
    {
      id: "@andrew_sanchez11@mail.com",
      name: "Andrew Sanchez",
      type: "kowloon",
      inbox: "https://mail.com/@andrew_sanchez11@mail.com/inbox",
      outbox: "https://mail.com/@andrew_sanchez11@mail.com/outbox",
      serverId: "@mail.com",
      url: "https://blushing-headquarters.info/",
    },
    {
      id: "@chloe_baker55@protonmail.com",
      name: "Chloe Baker",
      type: "kowloon",
      inbox: "https://protonmail.com/@chloe_baker55@protonmail.com/inbox",
      outbox: "https://protonmail.com/@chloe_baker55@protonmail.com/outbox",
      serverId: "@protonmail.com",
      url: "https://tedious-smell.info",
    },
    {
      id: "@charles_johnson82@outlook.com",
      name: "Charles Johnson",
      type: "kowloon",
      inbox: "https://outlook.com/@charles_johnson82@outlook.com/inbox",
      outbox: "https://outlook.com/@charles_johnson82@outlook.com/outbox",
      serverId: "@outlook.com",
      url: "https://annual-raven.name",
    },
    {
      id: "@paul_lee23@aol.com",
      name: "Paul Lee",
      type: "kowloon",
      inbox: "https://aol.com/@paul_lee23@aol.com/inbox",
      outbox: "https://aol.com/@paul_lee23@aol.com/outbox",
      serverId: "@aol.com",
      url: "https://jagged-handover.name",
    },
    {
      id: "@kimberly_turner44@gmail.com",
      name: "Kimberly Turner",
      type: "kowloon",
      inbox: "https://gmail.com/@kimberly_turner44@gmail.com/inbox",
      outbox: "https://gmail.com/@kimberly_turner44@gmail.com/outbox",
      serverId: "@gmail.com",
      url: "https://acrobatic-bricklaying.net/",
    },
    {
      id: "@noah_wright65@icloud.com",
      name: "Noah Wright",
      type: "kowloon",
      inbox: "https://icloud.com/@noah_wright65@icloud.com/inbox",
      outbox: "https://icloud.com/@noah_wright65@icloud.com/outbox",
      serverId: "@icloud.com",
      url: "https://hoarse-shaker.com",
    },
    {
      id: "@sofia_miller98@yahoo.com",
      name: "Sofia Miller",
      type: "kowloon",
      inbox: "https://yahoo.com/@sofia_miller98@yahoo.com/inbox",
      outbox: "https://yahoo.com/@sofia_miller98@yahoo.com/outbox",
      serverId: "@yahoo.com",
      url: "https://excellent-dish.info/",
    },
    {
      id: "@tommy_jenkins56@aol.com",
      name: "Tommy Jenkins",
      type: "kowloon",
      inbox: "https://aol.com/@tommy_jenkins56@aol.com/inbox",
      outbox: "https://aol.com/@tommy_jenkins56@aol.com/outbox",
      serverId: "@aol.com",
      url: "https://rotten-dresser.biz",
    },
    {
      id: "@aiden_scott29@mail.com",
      name: "Aiden Scott",
      type: "kowloon",
      inbox: "https://mail.com/@aiden_scott29@mail.com/inbox",
      outbox: "https://mail.com/@aiden_scott29@mail.com/outbox",
      serverId: "@mail.com",
      url: "https://periodic-grain.net",
    },
    {
      id: "@bella_thomas32@outlook.com",
      name: "Bella Thomas",
      type: "kowloon",
      inbox: "https://outlook.com/@bella_thomas32@outlook.com/inbox",
      outbox: "https://outlook.com/@bella_thomas32@outlook.com/outbox",
      serverId: "@outlook.com",
      url: "https://likable-pagoda.biz",
    },
    {
      id: "@zachary_evans71@gmail.com",
      name: "Zachary Evans",
      type: "kowloon",
      inbox: "https://gmail.com/@zachary_evans71@gmail.com/inbox",
      outbox: "https://gmail.com/@zachary_evans71@gmail.com/outbox",
      serverId: "@gmail.com",
      url: "https://unwilling-instrumentation.org/",
    },
    {
      id: "@grace_king13@yahoo.com",
      name: "Grace King",
      type: "kowloon",
      inbox: "https://yahoo.com/@grace_king13@yahoo.com/inbox",
      outbox: "https://yahoo.com/@grace_king13@yahoo.com/outbox",
      serverId: "@yahoo.com",
      url: "https://average-tracksuit.biz",
    },
    {
      id: "@alexandra_lee40@icloud.com",
      name: "Alexandra Lee",
      type: "kowloon",
      inbox: "https://icloud.com/@alexandra_lee40@icloud.com/inbox",
      outbox: "https://icloud.com/@alexandra_lee40@icloud.com/outbox",
      serverId: "@icloud.com",
      url: "https://scarce-donor.org",
    },
    {
      id: "@thomas_campbell81@protonmail.com",
      name: "Thomas Campbell",
      type: "kowloon",
      inbox: "https://protonmail.com/@thomas_campbell81@protonmail.com/inbox",
      outbox: "https://protonmail.com/@thomas_campbell81@protonmail.com/outbox",
      serverId: "@protonmail.com",
      url: "https://soupy-employ.org/",
    },
    {
      id: "@victor_adams69@aol.com",
      name: "Victor Adams",
      type: "kowloon",
      inbox: "https://aol.com/@victor_adams69@aol.com/inbox",
      outbox: "https://aol.com/@victor_adams69@aol.com/outbox",
      serverId: "@aol.com",
      url: "https://responsible-carry.name",
    },
    {
      id: "@amelia_bennett64@mail.com",
      name: "Amelia Bennett",
      type: "kowloon",
      inbox: "https://mail.com/@amelia_bennett64@mail.com/inbox",
      outbox: "https://mail.com/@amelia_bennett64@mail.com/outbox",
      serverId: "@mail.com",
      url: "https://cheerful-soundness.info",
    },
    {
      id: "@james_bradley53@gmail.com",
      name: "James Bradley",
      type: "kowloon",
      inbox: "https://gmail.com/@james_bradley53@gmail.com/inbox",
      outbox: "https://gmail.com/@james_bradley53@gmail.com/outbox",
      serverId: "@gmail.com",
      url: "https://active-image.name/",
    },
    {
      id: "@lily_harper50@icloud.com",
      name: "Lily Harper",
      type: "kowloon",
      inbox: "https://icloud.com/@lily_harper50@icloud.com/inbox",
      outbox: "https://icloud.com/@lily_harper50@icloud.com/outbox",
      serverId: "@icloud.com",
      url: "https://real-manufacturer.info",
    },
    {
      id: "@jordan_russell28@hotmail.com",
      name: "Jordan Russell",
      type: "kowloon",
      inbox: "https://hotmail.com/@jordan_russell28@hotmail.com/inbox",
      outbox: "https://hotmail.com/@jordan_russell28@hotmail.com/outbox",
      serverId: "@hotmail.com",
      url: "https://eminent-square.biz",
    },
    {
      id: "@madeline_green77@mail.com",
      name: "Madeline Green",
      type: "kowloon",
      inbox: "https://mail.com/@madeline_green77@mail.com/inbox",
      outbox: "https://mail.com/@madeline_green77@mail.com/outbox",
      serverId: "@mail.com",
      url: "https://hefty-partner.net/",
    },
    {
      id: "@nathaniel_gray22@aol.com",
      name: "Nathaniel Gray",
      type: "kowloon",
      inbox: "https://aol.com/@nathaniel_gray22@aol.com/inbox",
      outbox: "https://aol.com/@nathaniel_gray22@aol.com/outbox",
      serverId: "@aol.com",
      url: "https://muddy-corporatism.biz",
    },
    {
      id: "@ella_williams12@outlook.com",
      name: "Ella Williams",
      type: "kowloon",
      inbox: "https://outlook.com/@ella_williams12@outlook.com/inbox",
      outbox: "https://outlook.com/@ella_williams12@outlook.com/outbox",
      serverId: "@outlook.com",
      url: "https://sizzling-word.com",
    },
    {
      id: "@william_king57@gmail.com",
      name: "William King",
      type: "kowloon",
      inbox: "https://gmail.com/@william_king57@gmail.com/inbox",
      outbox: "https://gmail.com/@william_king57@gmail.com/outbox",
      serverId: "@gmail.com",
      url: "https://luminous-granny.com/",
    },
    {
      id: "@zara_stewart65@yahoo.com",
      name: "Zara Stewart",
      type: "kowloon",
      inbox: "https://yahoo.com/@zara_stewart65@yahoo.com/inbox",
      outbox: "https://yahoo.com/@zara_stewart65@yahoo.com/outbox",
      serverId: "@yahoo.com",
      url: "https://memorable-polyester.info",
    },
    {
      id: "@ethan_thompson19@icloud.com",
      name: "Ethan Thompson",
      type: "kowloon",
      inbox: "https://icloud.com/@ethan_thompson19@icloud.com/inbox",
      outbox: "https://icloud.com/@ethan_thompson19@icloud.com/outbox",
      serverId: "@icloud.com",
      url: "https://colorless-belfry.org",
    },
    {
      id: "@lauren_martinez77@mail.com",
      name: "Lauren Martinez",
      type: "kowloon",
      inbox: "https://mail.com/@lauren_martinez77@mail.com/inbox",
      outbox: "https://mail.com/@lauren_martinez77@mail.com/outbox",
      serverId: "@mail.com",
      url: "https://colorless-wild.com/",
    },
    {
      id: "@jared_evans22@protonmail.com",
      name: "Jared Evans",
      type: "kowloon",
      inbox: "https://protonmail.com/@jared_evans22@protonmail.com/inbox",
      outbox: "https://protonmail.com/@jared_evans22@protonmail.com/outbox",
      serverId: "@protonmail.com",
      url: "https://immense-flood.org/",
    },
    {
      id: "@emily_scott14@aol.com",
      name: "Emily Scott",
      type: "kowloon",
      inbox: "https://aol.com/@emily_scott14@aol.com/inbox",
      outbox: "https://aol.com/@emily_scott14@aol.com/outbox",
      serverId: "@aol.com",
      url: "https://staid-viability.net/",
    },
    {
      id: "@ryan_brown61@outlook.com",
      name: "Ryan Brown",
      type: "kowloon",
      inbox: "https://outlook.com/@ryan_brown61@outlook.com/inbox",
      outbox: "https://outlook.com/@ryan_brown61@outlook.com/outbox",
      serverId: "@outlook.com",
      url: "https://spicy-body.net/",
    },
    {
      id: "@victoria_fisher32@gmail.com",
      name: "Victoria Fisher",
      type: "kowloon",
      inbox: "https://gmail.com/@victoria_fisher32@gmail.com/inbox",
      outbox: "https://gmail.com/@victoria_fisher32@gmail.com/outbox",
      serverId: "@gmail.com",
      url: "https://belated-pentagon.com",
    },
    {
      id: "@ian_williams83@mail.com",
      name: "Ian Williams",
      type: "kowloon",
      inbox: "https://mail.com/@ian_williams83@mail.com/inbox",
      outbox: "https://mail.com/@ian_williams83@mail.com/outbox",
      serverId: "@mail.com",
      url: "https://striped-rugby.org",
    },
    {
      id: "@katherine_garcia49@icloud.com",
      name: "Katherine Garcia",
      type: "kowloon",
      inbox: "https://icloud.com/@katherine_garcia49@icloud.com/inbox",
      outbox: "https://icloud.com/@katherine_garcia49@icloud.com/outbox",
      serverId: "@icloud.com",
      url: "https://average-hackwork.info",
    },
    {
      id: "@max_hughes31@aol.com",
      name: "Max Hughes",
      inbox: "https://aol.com/@max_hughes31@aol.com/inbox",
      outbox: "https://aol.com/@max_hughes31@aol.com/outbox",
      serverId: "@aol.com",
      url: "https://oily-consonant.com/",
    },
  ];

  let circles = await Circle.find({});
  // let users = await User.find({});

  for (let i = 0; i < circles.length; i++) {
    let cmembers = users.sort(() => 0.5 > Math.random());

    try {
      await Circle.findOneAndUpdate(
        { id: circles[i].id },
        { $push: { members: cmembers } }
      );
    } catch (e) {
      console.log(e);
    }
  }
  return circles;
}
