// setup/server.js
// Kowloon installation wizard server.
// Serves the installer UI, validates input, writes .env + docker-compose.yml
// + Caddyfile to /config (mounted volume), then exits so install.sh can
// proceed with `docker compose up`.

import express from "express";
import { writeFileSync, existsSync } from "fs";
import { createRequire } from "module";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import crypto from "crypto";
import dns from "dns/promises";
import os from "os";

const __dirname = dirname(fileURLToPath(import.meta.url));
const app = express();
const PORT = 2999;
const CONFIG_DIR = process.env.CONFIG_DIR || "/config";

app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ── Routes ────────────────────────────────────────────────────────────────────

app.get("/", (_req, res) => {
  res.sendFile(join(__dirname, "index.html"));
});

// Already configured?
app.get("/status", (_req, res) => {
  res.json({ configured: existsSync(join(CONFIG_DIR, ".env")) });
});

// DNS check — non-blocking, returns whether domain resolves
app.get("/check-dns", async (req, res) => {
  const domain = String(req.query.domain || "").trim();
  if (!domain) return res.json({ ok: false, error: "No domain provided" });
  try {
    const addresses = await dns.resolve4(domain);
    const serverIp = getServerIp();
    const pointsHere = serverIp ? addresses.includes(serverIp) : null;
    res.json({ ok: true, addresses, serverIp, pointsHere });
  } catch {
    res.json({ ok: false, addresses: [], serverIp: getServerIp() });
  }
});

// Main install endpoint
app.post("/setup", async (req, res) => {
  const {
    domain,
    siteTitle,
    adminUsername,
    adminDisplayName,
    adminEmail,
    adminPassword,
    smtpHost,
    smtpPort,
    smtpUser,
    smtpPass,
  } = req.body;

  // ── Validate ────────────────────────────────────────────────────────────────
  const errors = [];
  if (!domain?.trim())          errors.push("Domain is required.");
  if (!siteTitle?.trim())       errors.push("Site name is required.");
  if (!adminUsername?.trim())   errors.push("Username is required.");
  if (!/^[a-z0-9_]{2,32}$/.test(adminUsername?.trim() ?? ""))
    errors.push("Username must be 2–32 lowercase letters, numbers, or underscores.");
  if (!adminEmail?.trim())      errors.push("Admin email is required.");
  if (!adminPassword || adminPassword.length < 10)
    errors.push("Password must be at least 10 characters.");

  if (errors.length) return res.status(400).json({ errors });

  // ── Generate secrets ────────────────────────────────────────────────────────
  const jwtSecret    = crypto.randomBytes(48).toString("base64url");
  const s3AccessKey  = crypto.randomBytes(12).toString("hex");
  const s3SecretKey  = crypto.randomBytes(24).toString("hex");
  const cleanDomain  = domain.trim().toLowerCase().replace(/^https?:\/\//, "");
  const cleanTitle   = siteTitle.trim();
  const cleanUser    = adminUsername.trim().toLowerCase();
  const displayName  = (adminDisplayName?.trim()) || cleanUser;

  // ── Write .env ──────────────────────────────────────────────────────────────
  const smtpLines = smtpHost?.trim()
    ? [
        `SMTP_HOST=${smtpHost.trim()}`,
        `SMTP_PORT=${smtpPort?.trim() || "587"}`,
        `SMTP_USER=${smtpUser?.trim() || ""}`,
        `SMTP_PASS=${smtpPass?.trim() || ""}`,
      ].join("\n")
    : "# SMTP_HOST=\n# SMTP_PORT=587\n# SMTP_USER=\n# SMTP_PASS=";

  const envContent = `# Kowloon — generated by installer on ${new Date().toISOString()}
# You can edit this file to change settings, then restart with: docker compose restart

NODE_ENV=production
PORT=3000

# ── Identity ──────────────────────────────────────────────────────────────────
DOMAIN=${cleanDomain}
SITE_TITLE=${cleanTitle}

# ── Admin account (used on first boot only; safe to remove after setup) ───────
ADMIN_EMAIL=${adminEmail.trim()}
ADMIN_USERNAME=${cleanUser}
ADMIN_DISPLAY_NAME=${displayName}
ADMIN_PASSWORD=${adminPassword}

# ── Database ──────────────────────────────────────────────────────────────────
MONGO_URI=mongodb://mongo:27017/kowloon

# ── Security ──────────────────────────────────────────────────────────────────
JWT_SECRET=${jwtSecret}

# ── File storage (local by default; switch to s3 for production scale) ────────
STORAGE_ADAPTER=local

# ── Email (optional — notifications won't send without this) ──────────────────
${smtpLines}
`;

  // ── Write Caddyfile ─────────────────────────────────────────────────────────
  const caddyContent = `# Managed by Kowloon — do not edit directly.
# Caddy will automatically obtain a TLS certificate via Let's Encrypt.

${cleanDomain} {
    reverse_proxy app:3000
}
`;

  // ── Write docker-compose.yml ────────────────────────────────────────────────
  const composeContent = `# Kowloon — generated by installer on ${new Date().toISOString()}
# Manage with: docker compose up/down/restart/logs

services:

  # ── Application ─────────────────────────────────────────────────────────────
  app:
    image: ghcr.io/kowloon/kowloon:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - uploads:/app/uploads
    networks:
      - internal

  # ── Background workers ───────────────────────────────────────────────────────
  worker-feed:
    image: ghcr.io/kowloon/kowloon:latest
    restart: unless-stopped
    command: node workers/feedFanOut.js
    env_file: .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - internal

  worker-outbox:
    image: ghcr.io/kowloon/kowloon:latest
    restart: unless-stopped
    command: node workers/outboxPush.js
    env_file: .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - internal

  worker-pull:
    image: ghcr.io/kowloon/kowloon:latest
    restart: unless-stopped
    command: node workers/federationPull.js
    env_file: .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - internal

  # ── Database ─────────────────────────────────────────────────────────────────
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  # ── Reverse proxy + automatic TLS ────────────────────────────────────────────
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - internal

volumes:
  mongo_data:
  uploads:
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
`;

  try {
    writeFileSync(join(CONFIG_DIR, ".env"),              envContent,     "utf8");
    writeFileSync(join(CONFIG_DIR, "Caddyfile"),         caddyContent,   "utf8");
    writeFileSync(join(CONFIG_DIR, "docker-compose.yml"),composeContent, "utf8");
  } catch (err) {
    console.error("Failed to write config files:", err.message);
    return res.status(500).json({ errors: ["Could not write config files: " + err.message] });
  }

  console.log(`Setup complete for ${cleanDomain}. Exiting so install.sh can start the stack.`);
  res.json({ ok: true, domain: cleanDomain });

  // Give the response time to reach the browser before the process exits.
  setTimeout(() => process.exit(0), 1500);
});

// ── Start ─────────────────────────────────────────────────────────────────────

app.listen(PORT, "0.0.0.0", () => {
  console.log(`Kowloon installer ready on port ${PORT}`);
});

// ── Helpers ───────────────────────────────────────────────────────────────────

function getServerIp() {
  try {
    const ifaces = os.networkInterfaces();
    for (const name of Object.keys(ifaces)) {
      if (name.startsWith("lo")) continue;
      for (const iface of ifaces[name]) {
        if (iface.family === "IPv4" && !iface.internal) return iface.address;
      }
    }
  } catch {}
  return null;
}
